# Site settings
title: 16.410 PADM  
subtitle: Principles of Autonomy and Decision Making 
description: |
  This course surveys a variety of reasoning, optimization and decision making methodologies for creating highly autonomous systems and decision support aids. The focus is on principles, algorithms, and their application, taken from the disciplines of artificial intelligence and operations research. Reasoning paradigms include logic and deduction, heuristic and constraint-based search, model-based reasoning, planning and execution, and machine learning. Optimization paradigms include linear programming, integer programming, and dynamic programming. Decision-making paradigms include decision theoretic planning, and Markov decision processes.
baseurl: ""
url: "http://padm.csail.mit.edu"
# baseurl: "/principles-of-autonomy-and-decision-making" # the subpath of your site, e.g. /blog/
# url: "https://mit-mers.gitlab.io" # the base hostname & protocol for your site
githubdir: "courses/principles-of-autonomy-and-decision-making"

# Author/user information
email: williams@csail.mit.edu
authorurl: "https://groups.csail.mit.edu/mers/"
address: |
  32-277, Stata Center
  Massachusetts Institute of Technology
  Computer Science & Artificial Intelligence Laboratory
  32 Vassar St, Cambridge MA 02139

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title

include: ['_images', '_css']
